### ISSUE TITLE
Add enable toggle

### ISSUE THREAD

**Issue by ghifari160** [Ghifari160/vtt-observe#2]
Currently, the vtt-observe is always enabled upon installation. That means when the user loads into a Roll20 campaign, vtt-observe will _always_ remove their UI elements. The current workaround is to disable the extension as a whole from `chrome://extensions`. This is not preferable. We should add a toggle.

**Comment by GiienaAstrella** [comment]
Implemented in f999d38fda45e93f69336593d63d6ea5c505484a.
