### ISSUE TITLE
Config entries in popup UI are not persistent when the service worker goes inactive

### ISSUE THREAD

**Issue by ghifari160** [Ghifari160/vtt-observe#5]
### Version

0.3.0 commit cf145d84f37e4ab51b03b881bdc7023903b1cb0e

### Chrome Version

108.0.5359.124 (Official Build) (x86_64)

### VTT

Roll20

### What Happened

When opening the popup page, the config entries resets back to the default state. The entries should persist regardless of how many times the popup is opened and closed.

### Present in latest version?

- [X] Yes

**Comment by GiienaAstrella** [comment]
Persistence is lost when the service worker goes inactive. It's likely that local storage is needed.
